# fly.toml app configuration file generated for political-map on 2026-05-04T01:21:47Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'political-map'
primary_region = 'iad'

[build]

[env]
  PGE_DB_PATH = '/data/pge.db'

[[mounts]]
  source = 'pge_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
